version: '3'

services:
  php:
    container_name: 'php'
    # image: 'php:7.2.11-fpm'
    build: './php'
    volumes:
      - ./src:/usr/share/nginx/html

  web:
    image: 'nginx:1.15.5'
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  db_postgres:
    image: 'postgres:11.0'
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  db_mysql:
    image: 'mysql'
    ports: 
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_DATABASE=mysql