-- GetSetPro
CREATE USER gsp WITH ENCRYPTED PASSWORD 'gsp';
CREATE DATABASE gsp OWNER gsp;
GRANT ALL PRIVILEGES ON DATABASE gsp TO gsp;

-- GetSetSocial
CREATE USER gss WITH ENCRYPTED PASSWORD 'gss';
CREATE DATABASE gss OWNER gss;
GRANT ALL PRIVILEGES ON DATABASE gss TO gss;

-- EAS
CREATE USER eas WITH ENCRYPTED PASSWORD 'eas';
CREATE DATABASE eas OWNER eas;
GRANT ALL PRIVILEGES ON DATABASE eas TO eas;

-- GMB
CREATE USER gmb WITH ENCRYPTED PASSWORD 'gmb';
CREATE DATABASE gmb OWNER gmb;
GRANT ALL PRIVILEGES ON DATABASE gmb TO gmb;